services:
  mongodb:
    image: mongo:6.0
    container_name: file-uploader-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=file_uploader_bd
    networks:
      - file-uploader-network

  minio:
    image: minio/minio:latest
    container_name: file-uploader-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - file-uploader-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-uploader-app
    restart: unless-stopped
    depends_on:
      - mongodb
      - minio
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/file_uploader_bd
      STORAGE_S3_ENDPOINT: http://minio:9000
      STORAGE_S3_ACCESS_KEY: minioadmin
      STORAGE_S3_SECRET_KEY: minioadmin123
      STORAGE_S3_BUCKET: uploads
      STORAGE_S3_REGION: us-east-1
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - file-uploader-network


networks:
  file-uploader-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  minio_data:
    driver: local